const COLORS = {
  CRYSTAL: "#A0CFD3",
  MOONSTONE: "#35A5BB",
  FADED_WHITE: "#FFFFFFB3",
  WHITE: "#FFFFFF",
  MOONSTONE_BLUE: "#75BECC",
  WATER: "#D1F5FF",
  DEEP_SPACE_SPARKLE: "#416165",
  LAPIS_LAZULI: "#207BA1",
};
//
export default COLORS;
