const COLORS = {
  CRYSTAL: "#A0CFD3",
  AURERISH_WHITE: "#D9ECED",
  MOONSTONE: "#35A5BB",
  FADED_WHITE: "#FFFFFFB3",
  WHITE: "#FFFFFF",
  MOONSTONE_BLUE: "#75BECC",
  WATER: "#D1F5FF",
  DEEP_SPACE_SPARKLE: "#416165",
  LAPIS_LAZULI: "#207BA1",
  PLATINUM: "#E8E8E8",
  LIGHT_GREY: "#D3D3D3",
  RED: "#FF0000",
  LEMON_YELLOW: "#FFFF9F",
  YELLOW: "#FFE417",
  ROYAL_GOLD: "#F5BD02",
  ORANGE: "#FF9900",
};
//
export default COLORS;
