export const QUESTIONNAIRE_ANSWERS = {
  NOT_AT_ALL: "Not at all",
  SEVERAL_DAYS: "Several days",
  MORE_THAN_HALF_DAYS: "More than half the days",
  NEARLY_EVERYDAY: "Nearly every day",
};
//
export const POINTS_OF_QUESTIONNARIE_ANSWERS = {
  [QUESTIONNAIRE_ANSWERS.NOT_AT_ALL]: 0,
  [QUESTIONNAIRE_ANSWERS.SEVERAL_DAYS]: 1,
  [QUESTIONNAIRE_ANSWERS.MORE_THAN_HALF_DAYS]: 2,
  [QUESTIONNAIRE_ANSWERS.NEARLY_EVERYDAY]: 3,
};
